[project]
name = "qacademico"
version = "0.1.0"
description = "Biblioteca para acesso de dados no QAcadÃªmico."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pydantic>=2.12.4", "beautifulsoup4>=4.14.2", "httpx>=0.28.1"]
